### ISSUE TITLE
VAAPI does not work

### ISSUE THREAD

**Issue by AngryPenguinPL** [OpenMandrivaAssociation/chromium-browser-stable#3]
Chromium after apply this vaapi [patch](https://github.com/OpenMandrivaAssociation/chromium-browser-stable/blob/master/enable-vaapi.patch), builds correctly, but Chromium built in this way for some (unknown to us) reason does not use vaapi to decode video.
We don't know what is the reason, maybe we have forgotten something. I will add that most of the Chromium changes in OpenMandriva Chromium are in sync with those of Fedora.

Last commit in chromium for openmandriva:
https://github.com/OpenMandrivaAssociation/chromium-browser-stable/commits/master
RPM packages: https://abf.openmandriva.org/build_lists/675434

More details can be provided by @berolinux , who made the last changes.

At this point I would like to ask for help, creator of the vaapi patch for chromium @akarshanbiswas
We are just before the new OpenMandriva Lx 4.1 release and we really need help with vaapi in chromium. We will be grateful for any help.

**Comment by AngryPenguinPL** [comment]
Chrome flags enabled: 
Override software rendering list
Hardware-accelerated video decode

I don't see anything useful in console, but here is output from launch to watch h264 video on YouTube.
```

[x@openmandriva-cooker ~]$ chromium-browser-stable
[34160:34160:0124/011211.041641:ERROR:sandbox_linux.cc(372)] InitializeSandbox() called with multiple threads in process gpu-process.
[34160:34160:0124/011225.365583:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[34193:1:0124/011229.729948:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[34193:1:0124/011229.731856:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[34230:1:0124/011239.146973:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[34230:1:0124/011239.148772:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[34230:1:0124/011239.151606:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[34230:1:0124/011239.181044:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[34230:1:0124/011240.682016:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[34230:1:0124/011240.685067:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[34272:1:0124/011248.098199:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[34272:1:0124/011248.102545:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[34272:1:0124/011248.106609:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[34272:1:0124/011248.109472:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
Fontconfig error: Cannot load default config file
[34272:1:0124/011252.135737:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
libx265.so.176: cannot open shared object file: Operation not permitted
libx265.so.176 is missing, x265 support will be disabled
[34350:1:0124/011306.158725:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[34350:1:0124/011306.160343:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.

```

**Comment by berolinux** [comment]
> libx265.so.176: cannot open shared object file: Operation not permitted

is not something to worry about - this is caused by our patch in ffmpeg that dlopens problematic codecs so it can play them if the libraries are installed, but will keep working if they aren't there (obviously without support for the codec in question).

You get this warning because you don't have libx265 installed, but it isn't needed anyway.

I'm not sure why vaapi isn't working, but it's unrelated to this.

**Comment by akarshanbiswas** [comment]
Hi. Please mention the environment here.(GPU, display-server,driver)

**Comment by AngryPenguinPL** [comment]
Trying on two computers, desktop pc and notebook.

OS: OpenMandriva Cooker (development branch)
GPU: Radeon HD 5850 and on notebook Radeon hd 5650m
Mesa 19.3.2
x-server 1.20.7
x11-driver-video-ati 19.1.0
Libva 2.6.1
Desktop Plasma 5.17.5
WM: KWIN
Kernel desktop 5.4.14 (tested both Clang and GCC version)

Output from vainfo:

```
[x@OpenMandriva-Cooker ~]$ vainfo
libva info: VA-API version 1.6.0
libva info: Trying to open /usr/lib64/dri/r600_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.6 (libva 2.6.0.0)
vainfo: Driver version: Mesa Gallium driver 19.3.2 for AMD CYPRESS (DRM 2.50.0 / 5.4.14-desktop-1omv4001, LLVM 9.0.1)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc

```

This issue is also confirmed by @berolinux and he has newer hardware, probably Vega?

BTW. VAAPI works fine for me on other browsers like Brave or Chromium downloaded from other distros.

**Comment by akarshanbiswas** [comment]
@AngryPenguinPL Try running a video and check outputs in chrome://media-internals.

**Comment by berolinux** [comment]
Actually I'm on an older box for the moment (at my father's place right now - using an older box I keep here, the Vega box is at home).

SW versions are the same as @AngryPenguinPL 's.

$ vainfo

libva info: VA-API version 1.6.0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.6 (libva 2.6.0.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Desktop - 2.4.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileH264StereoHigh         : VAEntrypointEncSlice
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileJPEGBaseline           : VAEntrypointVLD

**Comment by AngryPenguinPL** [comment]
> @AngryPenguinPL Try running a video and check outputs in chrome://media-internals.
> 
> Edit: Please share the build logs as well. Not sure how it is building successfully.
> I am unable to find BR:libva-devel

Ok, I added libva to buildrequires and started another build but from log from past builds I see that libva was pulled in anyway but not devels... Lets see another build.
```
Installing       : lib64va-drm2-2.6.1-1.x86_64                        415/522 
Installing       : lib64va-wayland2-2.6.1-1.x86_64                    416/522 
Installing       : lib64va-glx2-2.6.1-1.x86_64                        417/522 
Installing       : lib64va-x11_2-2.6.1-1.x86_64                       418/522 
Installing       : lib64va2-2.6.1-1.x86_64                            419/522
```
Here is rpm packages and in right corner you can find all build log: https://abf.openmandriva.org/build_lists/675434 (build log, root log, script output etc)
Or if you want directly link to build root: http://file-store.openmandriva.org/api/v1/file_stores/40d0075aabf9566956afdeb36ee3ae29b9ff0a46.log?show=true (big file +12MB)

I know chrome:media-internals, It show me on chromium: 

video_decoder | FFmpegVideoDecoder

But when I open Brave Browser (nightly release) then  I see working vaapi:


video_decoder | MojoVideoDecoder


Proof
Chromium

```
render_id: 6
player_id: 54
origin_url: https://www.youtube.com/
frame_url: https://www.youtube.com/watch?v=6fmIKH9npe0
frame_title: YouTube
surface_layer_mode: kAlways
url: blob:https://www.youtube.com/2b5cfcab-b237-4fce-bfa0-3accb6a16b2d
info: Effective playback rate changed from 0 to 1
pipeline_state: kPlaying
found_audio_stream: true
audio_codec_name: aac
duration: 10.286438
found_video_stream: true
video_codec_name: h264
audio_dds: false
audio_decoder: FFmpegAudioDecoder
is_platform_audio_decoder: false
video_dds: false
video_decoder: FFmpegVideoDecoder
is_platform_video_decoder: false
audio_buffering_state: BUFFERING_HAVE_ENOUGH
event: PAUSE
height: 720
width: 1280
video_buffering_state: BUFFERING_HAVE_ENOUGH
for_suspended_start: false
pipeline_buffering_state: BUFFERING_HAVE_ENOUGH

```


Brave

```
render_id: 23
player_id: 24
origin_url: https://www.youtube.com/
frame_url: https://www.youtube.com/watch?v=6fmIKH9npe0
frame_title: YouTube
surface_layer_mode: kAlways
url: blob:https://www.youtube.com/3d8b7d36-70de-4ccc-b649-8c4a33d604ce
info: Selected MojoVideoDecoder for video decoding, config: codec: h264, profile: h264 main, alpha_mode: is_opaque, coded size: [640,360], visible rect: [0,0,640,360], natural size: [640,360], has extra data: false, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}
pipeline_state: kSuspended
found_audio_stream: true
audio_codec_name: aac
duration: 10.286438
found_video_stream: true
video_codec_name: h264
event: SUSPENDED
audio_dds: false
audio_decoder: FFmpegAudioDecoder
is_platform_audio_decoder: false
video_dds: false
video_decoder: MojoVideoDecoder
is_platform_video_decoder: true
audio_buffering_state: BUFFERING_HAVE_ENOUGH
height: 360
width: 640
video_buffering_state: BUFFERING_HAVE_ENOUGH
for_suspended_start: false
pipeline_buffering_state: BUFFERING_HAVE_ENOUGH

```

**Comment by akarshanbiswas** [comment]
> render_id: 6
player_id: 54
origin_url: https://www.youtube.com/
frame_url: https://www.youtube.com/watch?v=6fmIKH9npe0
frame_title: YouTube
surface_layer_mode: kAlways
url: blob:https://www.youtube.com/2b5cfcab-b237-4fce-bfa0-3accb6a16b2d
info: Effective playback rate changed from 0 to 1
pipeline_state: kPlaying
found_audio_stream: true
audio_codec_name: aac
duration: 10.286438
found_video_stream: true
video_codec_name: h264
audio_dds: false
audio_decoder: FFmpegAudioDecoder
is_platform_audio_decoder: false
video_dds: false
video_decoder: FFmpegVideoDecoder
is_platform_video_decoder: false
audio_buffering_state: BUFFERING_HAVE_ENOUGH
event: PAUSE
height: 720
width: 1280
video_buffering_state: BUFFERING_HAVE_ENOUGH
for_suspended_start: false
pipeline_buffering_state: BUFFERING_HAVE_ENOUGH

I need the logs there.

**Comment by AngryPenguinPL** [comment]
@akarshanbiswas Thanks for help :)

VAAPI fixed by two commit:
https://github.com/OpenMandrivaAssociation/chromium-browser-stable/commit/afd314ed8776e5054ce54066a047fd2a726dfbd5
https://github.com/OpenMandrivaAssociation/chromium-browser-stable/commit/abd080f60f1b7ea09c3e48f569d654f2448ee7a4
